name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Install CocoaPods dependencies (если нужно)
        run: |
          cd plantify
          pod install || echo "No podfile, skipping"

      - name: Build App
        run: |
          xcodebuild -project plantify/plantify.xcodeproj \
                     -scheme plantify \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     build
